### ISSUE TITLE
Plant only prescription

### ISSUE THREAD

**Issue by lbross** [LANDIS-II-Foundation/Extension-Base-Harvest#3]
From Matthew:

What steps will reproduce the problem?
1. During a plant only prescription within "Biomass Harvest",

What is the expected output? What do you see instead?
It would be nice to be able to track how much a plant-only treatment is having on a landscape.  

Output maps and event-log.csv file for harvest treatments depend on > 0 amount of biomass removed for event to be triggered in outputs.  This does not work for plant only treatments.

What version of the product are you using? On what operating system?
Landis-II 6.0, Biomass Harvest v-2.0., Biomass Succession   v.3.0.

**Comment by lbross** [comment]
After reviewing the code, it appears that sites are scheduled for planting right after the cohorts are cut. So, if there are no cohorts to cut, they aren't scheduled for planting which is consistent with Matthew's report.

Matthew, can you provide a sample scenario (hopefully small) where planting is enabled and reflected in outputs? I can modify the sample scenario so no biomass is removed to develop/validate a solution.

**Comment by lbross** [comment]
From Eric:
It would be very helpful to have plant only available for re-entry harvest.  I would say it is high priority.  We need it for our big AFRI project, and I think Melissa has a deadline for those simulations to be run.

Lesley has received the sample scenario from Matthew.

**Comment by lbross** [comment]
I found an undocumented keyword for the CohortsRemoved parameter: PlantOnly. If this keyword is used in lieu of ClearCut or SpeciesList, the species are scheduled for planting but no harvesting occurs. Spoke with Matthew and he confirmed that this is the case. The species were planted by the PNet succession extension. This keyword needs to be added to the Base Harvest UG.

Matthew expressed an interest at somehow adding log information to report that planting had occurred. He is going to discuss with Rob. Perhaps logging for planting should be handled by the succession extension rather than harvest?

**Comment by lbross** [comment]
Plant only prescriptions do appear in the event log for Base Harvest in the format that Rob suggested. The first several columns contain information, but all the harvesting values are populated with zeroes. There is currently code in Biomass Harvest that prevents harvests from printing to the event log if no biomass is harvested. This, obviously, prevents entries from being written for plant only prescriptions. Just wanted to double-check and make sure it is okay to remove this condition. If it creates a problem for non plant only prescriptions that don't harvest anything, I could look into adding some sort of qualifier for plant-only prescriptions. Thoughts?

**Comment by bmarron18** [comment]
LBross made changes in Biomass Harvest so that output from PlantOnly prescriptions are written as they are in Base Harvest.  LBross' changes were checked by modifying an identical  prescription in both Base Harvest and  Biomass Harvest and comparing the "base-harvest-event-log.csv" to the   "biomass-harvest-event-log.csv". . In both cases, The fields, "Time", "ManagementArea", "Prescription", "Stand", "EventID",  "StandAge", "StandRank", and "NumberOfSites" all report data indicating that PlantOnly  was active. All other fields reported zero (ie no harvest).

QAQC passed; close issue.

[PWL84_QAQC_PlantOnly_20171005 .txt](https://github.com/LANDIS-II-Foundation/Extension-Base-Harvest/files/1360679/PWL84_QAQC_PlantOnly_20171005.txt)
